FROM node:22-alpine

WORKDIR /uis

# Copiamos solo los package.json primero (mejor cache de capas de Docker)
COPY website/package*.json ./website/
COPY backoffice/package*.json ./backoffice/

RUN cd website && npm ci
RUN cd backoffice && npm ci

# Ahora copiamos el resto del código fuente
COPY . .

EXPOSE 3000 3001

CMD ["sh", "./start.sh"]